version: '3'
services:
  web:
    image: "510124956856.dkr.ecr.eu-west-2.amazonaws.com/ecs-frontend"
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-frontend
        awslogs-region: eu-west-2
#        awslogs-stream-prefix: frontend
  api:
    image: "510124956856.dkr.ecr.eu-west-2.amazonaws.com/ecs-backend"
    ports:
      - "8080:8080"
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-backend
        awslogs-region: eu-west-2
#        awslogs-stream-prefix: backend
